{% set name = "marimo" %}
{% set version = "0.1.76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marimo-{{ version }}.tar.gz
  sha256: b8e29df2cd0c0d260c47581ffcccec510e6c6d597416d1f4235ea43318bde187

build:
  entry_points:
    - marimo = marimo._cli.cli:main
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - click >=8.0,<9
    - importlib-resources >=5.10.2  # [py<39]
    - jedi >=0.18.0
    - markdown >=3.4,<4
    - pymdown-extensions >=9.0,<11
    - pygments >=2.13,<3
    - tomlkit >=0.12.0
    - tornado >=6.1,<7
    - typing-extensions >=4.4.0  # [py<310]
    - black

test:
  imports:
    - marimo
  commands:
    - pip check
    - marimo --help
  requires:
    - pip

about:
  home: https://marimo.io
  dev_url: https://github.com/marimo-team/marimo
  summary: A library for making reactive notebooks and apps
  license: Apache-2.0
  license_file:
    - LICENSE
    - third_party.txt
    - third_party_licenses.txt

extra:
  recipe-maintainers:
    - mscolnick
    - akshayka
    - mfansler
