schema_version: 1

context:
  name: marimo
  version: "0.14.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/marimo-${{ version }}.tar.gz
  sha256: cf18513e30a5d2e8864930885b674dd89cbc9ad3a5e128b9ecfa48323de6d14f

build:
  skip:
    - ppc64le
    - aarch64
  number: 0
  python:
    entry_points:
      - marimo = marimo._cli.cli:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - click >=8.0,<9
    - jedi >=0.18.0
    - markdown >=3.4,<4
    - pymdown-extensions >=10,<11
    - pygments >=2.13,<3
    - tomlkit >=0.12.0
    - pyyaml >=6.0
    - uvicorn >=0.22.0
    - starlette >=0.26.1,!=0.36.0
    - websockets >=10
    - if: match(python, ">=3.11")
      then: loro >=1.5.0
    - if: match(python, "<3.11")
      then: typing-extensions >=4.4.0
    - docutils >=0.16.0
    - psutil >=5.0
    - itsdangerous >=2
    - narwhals >=1.12.0
    - ruff
    - packaging

tests:
  - python:
      imports:
        - marimo
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - marimo --help

about:
  summary: A library for making reactive notebooks and apps
  license: Apache-2.0
  license_file:
    - LICENSE
    - third_party.txt
    - third_party_licenses.txt
  homepage: https://marimo.io
  repository: https://github.com/marimo-team/marimo

extra:
  recipe-maintainers:
    - mscolnick
    - akshayka
    - mfansler
    - twrightsman
