schema_version: 1

context:
  name: marimo
  version: "0.19.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/marimo-${{ version }}.tar.gz
  sha256: eec3b765c3fd98d63e2017c56a024e779a6923cb56e7682e78876d4fe49409b7

build:
  skip:
    - ppc64le
    - aarch64
  number: 0
  dynamic_linking:
    binary_relocation: false
  python:
    entry_points:
      - marimo = marimo._cli.cli:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - uv-build
  host:
    - python
    - pip
    - uv-build
  run:
    - python
    - click >=8.0,<9
    - jedi >=0.18.0
    - markdown >=3.6,<4
    - pymdown-extensions >=10.15,<11
    - pygments >=2.19,<3
    - tomlkit >=0.12.0
    - pyyaml >=6.0
    - uvicorn >=0.22.0
    - starlette >=0.35.0,!=0.36.0
    - websockets >=14.2.0
    - if: match(python, ">=3.11")
      then: loro >=1.5.0
    - if: match(python, "<3.11")
      then: typing-extensions >=4.4.0
    - docutils >=0.16.0
    - psutil >=5.0
    - itsdangerous >=2
    - narwhals >=2.0.0
    - packaging
    - msgspec >=0.20.0

tests:
  - python:
      imports:
        - marimo
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - marimo --help

about:
  summary: A library for making reactive notebooks and apps
  license: Apache-2.0
  license_file:
    - LICENSE
    - marimo/third_party.txt
    - marimo/third_party_licenses.txt
  homepage: https://marimo.io
  repository: https://github.com/marimo-team/marimo

extra:
  recipe-maintainers:
    - mscolnick
    - akshayka
    - mfansler
